### ISSUE TITLE
Mega issue: expand modeling domain to IN, IA, SD, and ND

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/lake-temperature-model-prep#33]
This will need to be broken up into several issues, but I want to get it up here so we start thinking about the dependency chain and which parts of the project this is going to impact. 

- [x] ~We will need a new NHD subset that includes other potential lakes in those three new states~ see #35 
- [ ] we will need new cross-walks for any new state IDs (or MGLP IDs) to get them to NHD IDs
- [x] ~new WQP sites that include these other lakes~ see #36 
- [x] sources for clarity data
- [x] ~process NLCD buffers to get new sheltering numbers for new lakes~ see #39 
- [x] ~new drivers from NLDAS that include expansion of the footprint~ see #40 
- [x] new sources for max depth and/or hypsographic curves
- [ ] updated cooperator data for IN~ see #45

**Comment by aappling-usgs** [comment]
Also IA, right?

**Comment by jread-usgs** [comment]
Updated! Thanks

**Comment by jread-usgs** [comment]
While I'm in here thinking about this, it would be useful to get into the habit of having more summary targets for various stages in the future. For example, can I get a summary map plot of all of the NLDAS cells that we have drivers for? Can we get a map of lakes that have WQP sites in them? Coop sites/data, etc? These are useful for us, but also as gut check figures for our coop partners ("oh, I thought I uploaded data for X lake!?")

maybe this is easier given we have task_combiners available now? I also recognize that this would create additional work and I am probably on thin ice in that department!

**Comment by aappling-usgs** [comment]
I'm in favor of gut checks that ensure data quality. And yes, task_combiners should make them easier. Let's not preemptively create figures that we just think might be useful in the future, but anything that gives us useful feedback right now about whether we've succeeded in preparing the right data seems like fair game to me.

**Comment by jread-usgs** [comment]
for `new sources for max depth and/or hypsographic curve`, see https://portal.lternet.edu/nis/mapbrowse?packageid=knb-lter-ntl.320.1 which has many lakes that we already include in the MN,WI,MI footprint, but likely a bunch more for the other states (minus SD/ND). 

@limnoliver for ☝️do you know where the NHD IDs came from? Are they medium res? if so, are they permIDs or the other identifier? 
Also, do you know if LAGOS is compiling SD/ND depth data too?

**Comment by limnoliver** [comment]
These NHD IDs come from medium res. and yes are the permanent identifier. Iowa is in LAGOS.

My guess is yes to compiling depths for SD/ND but I'll ping someone to find out.

**Comment by jread-usgs** [comment]
Nice - 410 lakes in IA and IN have depths from LAGOS and are part of the MGLP subset. That's a good number for the project.

**Comment by jread-usgs** [comment]
For `we will need new cross-walks for any new state IDs (or MGLP IDs) to get them to NHD IDs`, I think we might want to go in the other direction - create a crosswalk to get the MGLP ID for the existing NHD IDs, since the medium res IDs we are using are essentially defunct.

**Comment by jread-usgs** [comment]
Closing this because "obtain crosswalks for new IDs" is kind of an endless task, and only relevant if we have a new data source that needs a crosswalk. The other item in here is captured in #45
